### ISSUE TITLE
CTAN

### ISSUE THREAD

**Issue by jgmbenoit** [dandrake/sagetex#4] opened 2016-08-10 08:56 UTC
Have you considered to update the SageTeX material at CTAN ?

**Comment by AndreC75** [comment] 2018-11-17 14:30
Very good question. 
If not, can you tell us how to update Sagetex on MikTeX with the latest version available on GitHub?

**Comment by jgmbenoit** [comment] 2018-11-17 14:40
No idea, but I think that MikTeX takes its material from CTAN (I have to confess that I have not played with MikTeX since the last century).

**Comment by dimpase** [comment] 2019-01-10 07:54
I'm in the process of getting a CTAN account. Not sure atm what exactly will be needed to be able to push an update.

**Comment by jgmbenoit** [comment] 2019-01-10 08:18
I have not idea either. But it is a good move.

**Comment by kcrisman** [comment] 2019-02-04 14:57
Is https://ctan.org/pkg/sagetex sufficient for @jgmbenoit ?

But ideally you only update SageTeX via Sage itself.

**Comment by jgmbenoit** [comment] 2019-02-04 15:31
Are you ironic ?
Anyway, I think it is a good idea to have any TeX  related package at CTAN since from CTAN it may propagate to TeX distributions as texlive or MikTeX. Having said that, SageTeX is also a Python package, so the propagation might not be obvious.
Concerning updates, as Debian maintainer of the SageTeX package, I still check against the GitHub material. Indeed. Please note that Debian is actually freezing: this period can get crazy, so nothing unreasonable should be made during this period. Otherwise, I would prefer to check and fetch SageTeX from CTAN, given that CTAN is the right place for TeX material. The question is now which is authoritative according to the SageTeX upstream team ?

**Comment by dimpase** [comment] 2019-02-04 18:04
@jgmbenoit from now on we will try to keep github and CTAN in sync, so either is good.

**Comment by dandrake** [comment] 2019-02-05 14:27
Just a note from my own experience: keeping github, Sage, and CTAN in sync will likely not be good enough, because TeX distributions may not keep up with CTAN. For example, Debian ships TeXLive but doesn't update it very frequently (at least that was true years ago). So many Debian users with a TeX installation will have an outdated sagetext.sty file around and encounter problems. And because the problem is with Debian's package, there's nothing the Sage community can do to fix the problem.

**Comment by dimpase** [comment] 2019-02-05 14:36
Well, at least having CTAN up to date will eliminate one discrepancy here. At the moment Debian is quite up to date with Sage...

**Comment by jgmbenoit** [comment] 2019-02-05 15:18
Concerning Debian, SageTeX is right now maintained separately from texlive stuff, even if it is maintained on behalf of the so called Debian TeX Maintainers team. Otherwise, because SageTeX involves Python, I am not so sure that SageTeX will go straight to texlive. I have no idea as a matter of fact. In practice, the Debian SageTeX package is maintained by me, and I also belong to the Sage Debian team. So, it should be fine for a while as concerns Debian.

**Comment by dimpase** [comment] 2019-06-10 10:57
OK, I'll close this; there is a new version of Sagetex to be releases soon, fixing few bugs.

**Closed as completed by dimpase** 2019-06-10 10:57 UTC
